import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { MovieContextProvider } from "../../context/MovieContext";

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <MovieContextProvider>{children}</MovieContextProvider>
      </body>
    </html>
  );
}
